apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-driver.fullname" . }}
  labels:
    {{- include "spark-driver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: 7078
      targetPort: 7078
      protocol: TCP
      name: driver-rpc-port
    - port: 7079
      targetPort: 7079
      protocol: TCP
      name: blockmanager
    - port: 4040
      targetPort: 4040
      protocol: TCP
      name: spark-ui
  selector:
    {{- include "spark-driver.selectorLabels" . | nindent 4 }}
